---
title: "Tema 3"
subtitle: Tratamiento de Datos. Grado en Ciencia de Datos- UV
author: "Visualiza Grupo P"
date:  "`r Sys.Date()`"  #Pondría la fecha del día actual
 
params:
  lang: ES
lang: "`r switch(params$lang, ES = 'es-ES', EN = 'en-US')`"
output:
  html_document:
    echo: yes
    number_sections: yes
    theme: lumen
    toc: yes
  html_notebook:
    echo: yes
    number_sections: yes
    toc: yes
  pdf_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
language:
  label:
    fig: 'Figura '
    tab: 'Tabla '
    eq: 'Ecuación '
    thm: 'Teorema '
    lem: 'Lema '
    def: 'Definición '
    cor: 'Corolario '
    prp: 'Proposición '
    exm: 'Ejemplo '
    exr: 'Ejercicio '
    proof: 'Demostración. '
    remark: 'Nota: '
    solution: 'Solución. '
---


```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}

# CONFIGURACIÓN GENERAL
library(knitr)
options(width = 100)
# Opciones generales chunks
opts_chunk$set(echo=T,message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 100, tidy = F, cache.path = '.cache/', fig.path = './figure/')

#options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
#knit_hooks$set(plot = knitr:::hook_plot_html)
```

## Imagen Covid

```{r}
# Cargamos las librerías que vamos a necesitar
library(tidyverse)
library(knitr)
library(htmltools)
library(plotly)
library(ggplot2)
library(datasets)
library(dplyr)
library(extrafont)
library(stringr)

# Carga de fuentes de letra adicionales
# Si no tienes descargadas las fuentes, ejecuta esto antes: font_import
loadfonts(device = "win", quiet = TRUE)

```